steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', '-t', 'gcr.io/docker-nextjs-graphql/nextgql', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['push', 'gcr.io/docker-nextjs-graphql/nextgql']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'nextgql'
      - '--image'
      - 'gcr.io/docker-nextjs-graphql/nextgql'
images: [gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA]
